import React, { useEffect, useState } from 'react';
import { DataTable } from "../../components/custom-web-controls/DataTable";
import { GenerateReportDetails } from '../../components/report-templates/GenerateReportDetails';
import { GenerateReportArchiveReportProps } from '../../interfaces/props/GenerateReportArchiveReportProps';
import { GenerateReportArchiveReportMockData } from '../../mockData/GenerateReportArchiveReportMockData';




export const GenerateReport = () => {
  let mappedData: GenerateReportArchiveReportProps[];  
  const [archiveReportsData, setArchiveReportsData] = useState<GenerateReportArchiveReportProps[]>([]);

  // Fetch from API
  // Might need to convert this in a custom hooks
  useEffect(() => {
    mappedData = GenerateReportArchiveReportMockData.map(report => {
      return {
        ...report        
      }
    });
  }, []);
    
  useEffect(() => {    
    mappedData && setArchiveReportsData(mappedData);
  },[archiveReportsData]);

  const archiveReportsTableHeader = [
    { heading : 'Document Name', value : 'documentName' }, 
    { heading: 'Generated By', value : 'generatedBy'},
    { heading: 'Belongs To', value : 'belongsTo'},
    { heading: 'From', value : 'from'},
    { heading: 'To', value : 'to'},
    { heading: 'Generation', value : 'generation'},
    { heading: 'Actions', value : 'actions'} 
  ];
  
  return (
    <>      
      <div className="content-wrapper">
        <div className="row">
          <GenerateReportDetails />
          <div className="col-md-12 grid-margin stretch-card">
            <div className="card">
              <div className="card-body">
                <div className="form-check">
                  <label className="form-check-label">
                    <input type="checkbox" className="form-check-input" />
                    Show Archived Reports
                    <i className="input-helper" />
                  </label>
                </div>
                <hr />  
                <DataTable headers={archiveReportsTableHeader} data={archiveReportsData}/>              
              </div>
            </div>
          </div>
        </div>
      </div>      
    </>
  )
}